language: php

php:
  - '5.5'

sudo: false

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit -c tests/Build/UnitTests.xml --coverage-clover build/logs/clover.xml
  - ./vendor/bin/test-reporter